-- CreateTable
CREATE TABLE "SiteSettings" (
    "id" TEXT NOT NULL DEFAULT 'singleton',
    "freeShippingThresholdCents" INTEGER NOT NULL DEFAULT 5000,
    "flatShippingCents" INTEGER NOT NULL DEFAULT 0,
    "brandName" TEXT NOT NULL DEFAULT 'Aileen''s petstore',
    "supportEmail" TEXT NOT NULL DEFAULT '',
    "tagline" TEXT NOT NULL DEFAULT '',
    "description" TEXT NOT NULL DEFAULT '',
    "logoAccentWords" INTEGER NOT NULL DEFAULT 1,
    "socialInstagram" TEXT,
    "socialFacebook" TEXT,
    "socialTwitter" TEXT,
    "heroEyebrow" TEXT NOT NULL DEFAULT '',
    "heroHeadline" TEXT NOT NULL DEFAULT '',
    "heroSubhead" TEXT NOT NULL DEFAULT '',
    "heroImageUrl" TEXT NOT NULL DEFAULT '/images/hero-placeholder.jpg',
    "heroPrimaryCtaLabel" TEXT NOT NULL DEFAULT '',
    "heroPrimaryCtaHref" TEXT NOT NULL DEFAULT '',
    "heroSecondaryCtaLabel" TEXT NOT NULL DEFAULT '',
    "heroSecondaryCtaHref" TEXT NOT NULL DEFAULT '',
    "brandValuesJson" JSONB NOT NULL DEFAULT '[]',
    "updatedAt" TIMESTAMP(3) NOT NULL,
    "updatedBy" TEXT,

    CONSTRAINT "SiteSettings_pkey" PRIMARY KEY ("id"),
    CONSTRAINT "SiteSettings_singleton_check" CHECK ("id" = 'singleton')
);

-- Seed singleton row (env-driven shipping defaults applied via prisma/seed.ts on deploy)
INSERT INTO "SiteSettings" (
    "id",
    "freeShippingThresholdCents",
    "flatShippingCents",
    "brandName",
    "supportEmail",
    "tagline",
    "description",
    "logoAccentWords",
    "heroEyebrow",
    "heroHeadline",
    "heroSubhead",
    "heroImageUrl",
    "heroPrimaryCtaLabel",
    "heroPrimaryCtaHref",
    "heroSecondaryCtaLabel",
    "heroSecondaryCtaHref",
    "brandValuesJson",
    "updatedAt"
) VALUES (
    'singleton',
    5000,
    599,
    'Aileen''s petstore',
    'hello@aileenspetstore.com',
    'Food they''ll actually love.',
    'Thoughtfully sourced, vet-approved nutrition for every pet.',
    1,
    'New season · vet approved',
    'Food they''ll actually love.',
    'Thoughtfully sourced, vet-approved nutrition for every pet.',
    '/images/hero-placeholder.jpg',
    'Shop now',
    '/products',
    'Browse categories',
    '#categories',
    '[{"title":"Free shipping","body":"On every order over $50, anywhere in the country.","icon":"truck"},{"title":"Vet approved","body":"Recipes formulated alongside practising veterinarians.","icon":"stethoscope"}]'::jsonb,
    CURRENT_TIMESTAMP
);
